# Site settings
title: Устрой дестрой 😈
email: vivkin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Соу мета дескрипшен моего космо-блога 😎
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vivkin.com" # the base hostname & protocol for your site
twitter_username: vivkin
github_username: vivkin

# Build settings
markdown: kramdown
